version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordForDB
      POSTGRES_DB: db_laba_servlets
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dbdata:
